import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header, Footer } from "@/components/sections";
import { HeaderThemeProvider } from "@/contexts/HeaderThemeContext";
import "@/styles/index.scss";
import '@/styles/root.scss';

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistInter.variable}>
        <HeaderThemeProvider>
          <Header/>
          <main className="main">
            {children}
          </main>
          <Footer/>
        </HeaderThemeProvider>
      </body>
    </html>
  );
}
